feat: ТЗ-13
MariaNzrv/java-shareit pull request #1
Opened 2024-04-24 21:22 UTC by MariaNzrv

ТЗ-13

2024-04-25 08:52 UTC, TomattmanYandex requested changes
Привет, работа хорошая, но есть что поправить

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +package ru.practicum.shareit.exception;
я бы рекомендовал хранить обработчик ошибок отдельно от самих ошибок, 
только для простоты воспринятия, и потому что сами ошибки относятся сразу ко всем слоям приложения, а обработчик ошибок только на уровне контроллера

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    String error;
модификаторы доступа

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/ConflictValidationException.java
> +public class ConflictValidationException extends ValidationException {
с одной стороны хорошо что есть несколько разных ошибок на разные случаи, с другой стороны, а зачем, если они ничем отличаться ну будут, кроме сообщения

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/ConflictValidationException.java
> +public class ConflictValidationException extends ValidationException {
хотя они отличаются по обработке в обработчике ошибок, так что все норм

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/exception/ConflictValidationException.java
> +public class ConflictValidationException extends ValidationException {
с другой стороны, можно поспорить о иерархии и относится ли ошибка конфликта к валидационным

это так полет мыслей, просто чтобы задуматься

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
аннотация autowired тут избыточна
инжект зависимостей идет через конструктор

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        for (Item item : items) {
а бы рекомендовал перегрузить метод toItemDto в маппере  чтобы принимал в себя еще и list и так получится хорошее разделение ответственности, маппер отвечает за маппинг и одного элемента и сразу списка

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        for (Item item : items) {
кстати еще по мапперу
если имя метода будет toDto то оно будет универсальное и придётся меньше задумываться при использовании маппера

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (!userStorage.isUserExist(userId)) {
тут есть тоже моменты как это поправить и сделать удобнее и читабельнее
1) не делать в хранилище метод проверяющий наличие. В большинстве случаев все равно будем потом получать этот объект
так почему бы не получить по идентификатору и потом сравнить c null
2) еще лучше сделать чтобы возвращал не объект а optional вокруг объекта, так будет еще удобнее ведь можно использовать orElseThrow
3) можно сделать отдельный метод getUserById
public User getUserById(Long id) {
return userStorage.getById(id).orElseThrow(() -> new RuntimeException("Пользователя с Id = " + userId + " не существует"));
} 
он делает то же самое что и строчки 27-30 (без логов) но можно переиспользовать
а для проверки наличичия пользователя, вызываешь этот метод, и если нет ошибки, то значит пользоватлеь существует

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getName() == null || itemDto.getDescription() == null || itemDto.getAvailable() == null) {
валидацию, для читаемости тоже бы вынести в отдельный метод

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getName() == null || itemDto.getDescription() == null || itemDto.getAvailable() == null) {
плюс можно добавить валидационные аннотации на Dto и в контроллере повесить на параметр аннотацию @Valid

2024-04-25 08:52 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getName() == null || itemDto.getDescription() == null || itemDto.getAvailable() == null) {
и в чем отличие этой проверки и проверки в методе validateFieldsFormat(itemDto);

2024-04-26 15:35 UTC, MariaNzrv commented on src/main/java/ru/practicum/shareit/exception/ConflictValidationException.java
> +public class ConflictValidationException extends ValidationException {
Мне нравится, когда есть полет мыслей =) вопрос принят к размышлению)

2024-04-26 17:44 UTC, MariaNzrv commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getName() == null || itemDto.getDescription() == null || itemDto.getAvailable() == null) {
Отличие в том, что возможно частичное обновление для Item. В этом случае, не все поля Dto, которые обязательны для заполнения при создании объекта, являются обязательными при его обновлении. Но формат полей, при их поступлении, надо проверить в обеих операциях. Поэтому данная проверка вынесена в отдельный метод для переиспользования кода.

2024-04-27 17:03 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    @Autowired
я не добавляю  везде однотипные комментарии, а то тут сейчас большинство классов однотипные, и будет просто много одинаковых коментов, но большинство коментов относится больше чем к одному, как например тут Autowired тоже не нужен так как инжект идет через конструктор

2024-04-27 17:03 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        if (itemDto.getName() == null || itemDto.getDescription() == null || itemDto.getAvailable() == null) {
Принято, аргументный аргумент

2024-04-27 17:03 UTC, TomattmanYandex approved these changes
ПРинято, хоть есть места которые были забыты

2024-04-29 16:42 UTC, merged