feat: ТЗ-15
MariaNzrv/java-shareit pull request #3
Opened 2024-05-30 18:21 UTC by MariaNzrv

feat: ТЗ-15

2024-05-31 08:28 UTC, TomattmanYandex requested changes
по основному коду вопросов почти нету, так улучшения
по тестам
1) не вижу интеграционных тестов
2) юнит тесты тоже стоило бы как то выделить ( это те который будут без моков тестировать взаимодействие слоев
3) имена тестовых методов
стандрартны шаблон для имен
в первую очерель имя самого тестируемого метода (ьез всякихх префиксов) то что это тест мы понимаем потому что этот метод в папке tests и по аннотации над ним
вторая часть - это что должно происходить, ведь для анализа теста мы должны понимать что в нем тестируется
третья часть, она не обязательная, но иногда тоже важна - при каких условиях, например если мы тестируем ошибку что что-то не найдено, нам важно указать, что мы тестируем конкретно этот случай
разделять части можно нижним подчеркиванием, или словами Should и When нижние подчеркивания читаются гораздо приятнее и удобнее (по моему)
Примеры
createItemRequest_throwNotFoundException_userNotExist
createItemRequestShouldThrowNotFoundExceptionWhenUserNotExist
по имени сразу понятно что мы делаем, какой метод тестируем, что должно произойти, и почему

еще примеры, оставлю только с нижним подчеркиванием
findAllBookingsOfUser_returnCorrectBookings_stateIsCurrent
findAllBookingsOfUser_returnCorrectBookings_stateIsPast
да по хорошему, при ветвении логики в методе, какждая ветка должна быть преверена,  и чаще всего в отдельном тесте
Есть тулы которые анализируют покрытие кода тестами, и они смотрят какие строчки кода были вызваны в тесте, а какие нет
а отдельные тесты, чтобы не переусложнять один конкретный тест, и чтобы если упал один, остальные работали корректно

2024-05-31 08:28 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (from == null || size == null) {
логичнее, если есть не обязательные параметры проставлять дефолтные значения, лучше на уровне контроллера, 
если мы добавляем в @RequestParam дефолтное значение, то он становится не обязательным автоматически

2024-05-31 08:28 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private Pageable validateBookingPageParams(Integer from, Integer size) {
стоит переиеновать метод, если он валидирует то не нужно чтобы он что то возвращал, если он что то возвращает но при этом с проверкой, то лучше назвать getPageble

2024-06-02 21:43 UTC, MariaNzrv commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (from == null || size == null) {
сделано

2024-06-02 21:43 UTC, MariaNzrv commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    private Pageable validateBookingPageParams(Integer from, Integer size) {
сделано

2024-06-04 08:38 UTC, TomattmanYandex approved these changes
Принято

2024-08-12 20:58 UTC, merged